#version: '3'

services:
  flask-webapp:
    image: ghcr.io/jalcocert/flask_sensor_display #flask_sensor
    container_name: flask_sensor_webapp
    volumes:
      - flask_webapp:/app
    working_dir: /app
    command: /bin/sh -c "\
      python3 app.py"
    #command: tail -f /dev/null 
    ports:
      - "9999:9999"
    restart: always
    environment:
      Platform: x300 #bme280 #pi4
    # networks:
    #   - cloudflare_tunnel
      # - nginx_default   
    #restart: always   

# networks:
#   cloudflare_tunnel:
#     external: true
  # nginx_default:
  #   external: true

volumes:
  flask_webapp:

#docker-compose up -d

#docker exec -it flask_sensor_webapp /bin/bash 